---
# Config Docker Repository
- name: Config Docker Repository
  debug: msg="docker_exist == {{ list_repositories.docker_exist }}"
  when: list_repositories.docker_exist | bool

- name: Add Docker GPG apt Key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.gpg
  when: list_repositories.docker_exist | bool

- name: Add Docker Repository
  apt_repository:
    repo: "deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  when: list_repositories.docker_exist | bool


# Config Hashicorp Repository
- name: Config Hashicorp Repository
  debug: msg="hashicorp_exist == {{ list_repositories.hashicorp_exist }}"
  when: list_repositories.hashicorp_exist | bool

- name: Add Hashicorp GPG apt Key
  get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /usr/share/keyrings/hashicorp-archive-keyring.gpg
  when: list_repositories.hashicorp_exist | bool

- name: Add Hashicorp Repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
  when: list_repositories.hashicorp_exist | bool


# Config Ansible Repository
- name: Config Ansible Repository
  debug: msg="ansible_exist == {{ list_repositories.ansible_exist }}"
  when: list_repositories.ansible_exist | bool

- name: Add Ansible Repository
  apt_repository:
    repo: ppa:ansible/ansible
    state: present
  when: list_repositories.ansible_exist | bool


# Config Jenkins Repository
- name: Config Jenkins Repository
  debug: msg="jenkins_exist == {{ list_repositories.jenkins_exist }}"
  when: list_repositories.jenkins_exist | bool

- name: Add Jenkins GPG apt Key
  get_url:
    url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
  when: list_repositories.jenkins_exist | bool

- name: Add Jenkins Repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/"
    state: present
  when: list_repositories.jenkins_exist | bool


# Update cache
- name: update apt cache
  apt:
    update_cache=yes
    cache_valid_time=3600
