---
# Config Docker Repository
- name: Config Docker Repository
  debug: msg="docker_exist == {{ list_repositories.docker_exist }}"
  when: list_repositories.docker_exist | bool

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  when: list_repositories.docker_exist | bool

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
  when: list_repositories.docker_exist | bool


# Config Terraform Repository
- name: Config Terraform Repository
  debug: msg="terraform_exist == {{ list_repositories.terraform_exist }}"
  when: list_repositories.terraform_exist | bool

- name: Add Terraform GPG apt Key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  when: list_repositories.terraform_exist | bool

- name: Add Terraform Repository
  apt_repository:
    repo: deb https://apt.releases.hashicorp.com focal main
    state: present
  when: list_repositories.terraform_exist | bool


# Config Ansible Repository
- name: Config Ansible Repository
  debug: msg="ansible_exist == {{ list_repositories.ansible_exist }}"
  when: list_repositories.ansible_exist | bool

- name: Add Ansible Repository
  apt_repository:
    repo: ppa:ansible/ansible
  when: list_repositories.ansible_exist | bool


# Update cache
- name: update apt cache
  apt:
    update_cache=yes
    cache_valid_time=3600
