---
- name: Clean SSH Access
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    line: "PasswordAuthentication no"
    state: absent
  register: sshd_config

- name: Restart SSH Service
  service:
    name: ssh
    state: restarted
  when: sshd_config.changed
